### ISSUE TITLE
Feature request: Allow batching from a raw query input

### ISSUE THREAD

**Issue by SippieCup** [gabfl/pg-batch#13]
Currently, I use an alternative script for this and I have no idea how active you want to be about development, but I figured I'd make an issue and see what you think.

A lot of batch jobs come down to removing duplicates, of which this tool would be great however its argument structure makes it less than ideal than just using a simple python script or something instead.

Take the query:
```
delete from somekeystore a 
	using  somekeystore b
      WHERE a.id < b.id and a.name = b.name and a.value = b.value and a.userid = b.userid
```

Lets say we want to remove all the duplicates key/value pairs in the `value` column for every user. This would be a great use case for your tool, but I have not found a way for this to work.

if there was an optional input argument of "raw_query" which only needs to be paired with write_batch_size, then this tool could become a bit more powerful than it currently is.

Thanks for your work. If I find time, I might be able to do it myself and do a PR.

**Comment by gabfl** [comment]
@SippieCup 

The program roughly works this way:

```sql
-- Fetching XX rows
SELECT id FROM some_table WHERE a = 123 ORDER BY id LIMIT 1000;

-- Updating them
UPDATE some_table SET a = 456 WHERE id IN (1, 2, 3, 4, 5, ..., 1000);

-- Then fetch more rows
SELECT id FROM some_table WHERE a = 123 AND id > 1000 ORDER BY id LIMIT 1000;

-- Update them and so on until there are no more rows to update
```

I am not sure how this concept could work with a raw query. PostgreSQL does not allow to add a LIMIT clause to queries so they would need to be selected first before calling the DELETE statement.

The easiest solution would be to create first a temporary table with he IDs of the rows to delete. then using `--where "id IN (SELECT id FROM delete_me)"`

**Comment by gabfl** [comment]
Closing the ticket since I did not hear back from you but feel free to re-open it if needed
