### ISSUE TITLE
pg_batch fails on table with non-integer primary keys

### ISSUE THREAD

**Issue by bjmc** [gabfl/pg-batch#5]
Thank you for making this useful tool!

Unfortunately, I ran into a problem trying to run it on a table that has a UUID primary key:

```
psycopg2.ProgrammingError: operator does not exist: character varying > integer
LINE 1: ...tokens WHERE expiry < NOW() AND token_id > 0 ORDER ...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```
I believe the problem is [this line,](https://github.com/gabfl/pg-batch/blob/master/src/pg_batch.py#L186)

>  sql = "SELECT {0} as id FROM ".format(args.primary_key) + args.table + " WHERE " + args.where + " AND {0} > %s ORDER BY {1} LIMIT %s".format(args.primary_key, args.primary_key)

That tries to compare the UUID primary key column against the integer number for the batch range.

Do you have any suggestions on how to resolve this? Are you accepting pull requests?

Thanks again for your work.

**Comment by gabfl** [comment]
Hi @bjmc,

The way the tool works is easy: if you have 1000 rows with an integer `id`, it will select rows 100 by 100, sorted by ID and go thru the table by increasing the `id` pointer at each loop.

I am not sure how that logic could be implemented with non numeric primary keys.

If you have a solution in mind, a pull request is very welcome.

**Comment by volkanto** [comment]
@bjmc did you find a way to do this?

**Comment by bjmc** [comment]
@volkanto Sorry this was four years and three jobs ago and I don't remember. I think I didn't use this tool. In principle I believe it should be possible to update this tool to handle non-integer IDs, but I haven't given it much thought.
